### ISSUE TITLE
Get rid of wildcard imports

### ISSUE THREAD

**Issue by honza-kasik** [jboss-eap-qe/eap-microprofile-test-suite#105]
Wildcard imports can lead to all sorts of issues when comes to maintenance. We should get rid of them.

@rsvoboda Does the formatter or import sorter you added support control of such imports?

**Comment by rsvoboda** [comment]
There should be a way, https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/ide-config/eclipse-format.xml is used by the plugin

http://www.eclipseonetips.com/2014/01/14/essential-tools-to-manage-import-statements-in-eclipse/
4. Let Eclipse collapse imports in the same package a wildcard (.*) or always expand them

IDE setup - https://stackoverflow.com/questions/3348816/intellij-never-use-wildcard-imports

**Comment by honza-kasik** [comment]
Thanks for the references - looks like these are the keys responsible for not replacing long list of imports by a wildcard:
```patch
diff --git a/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.ui.prefs b/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.ui.prefs
index 3eaf844..92fa5c2 100644
--- a/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.ui.prefs
+++ b/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.ui.prefs
@@ -2,6 +2,10 @@ content_assist_proposals_background=255,255,255
 content_assist_proposals_foreground=0,0,0
 eclipse.preferences.version=1
 org.eclipse.jdt.ui.formatterprofiles.version=17
+org.eclipse.jdt.ui.ignorelowercasenames=true
+org.eclipse.jdt.ui.importorder=java;javax;org;com;
+org.eclipse.jdt.ui.ondemandthreshold=0
+org.eclipse.jdt.ui.staticondemandthreshold=0
 spelling_locale_initialized=true
 useAnnotationsPrefPage=true
 useQuickDiffPrefPage=true
```

Though there are AFAIK no options for formatter to actually enforce this so adding this to `eclipse-formatter.xml` won't work:

```xml
<setting id="org.eclipse.jdt.ui.ondemandthreshold" value="0"/>
<setting id="org.eclipse.jdt.ui.staticondemandthreshold" value="0"/>
```

**Comment by rsvoboda** [comment]
We can use checkstyle to detect this - https://github.com/wildfly/wildfly-checkstyle-config/blob/master/src/main/resources/wildfly-checkstyle/checkstyle.xml#L23

Or we can do simple bashism in travis yaml
`git grep import | grep '\*' | grep -v '.mvn' | wc -l` needs to be 0

Enhancement for impsort:check to detect * imports was (rightfully) rejected
https://github.com/revelc/impsort-maven-plugin/issues/21

**Comment by mnovak1** [comment]
My experience with check style plugin is quite annoying. Thus I would prefer to add check into `.travis.yml`:
```
git grep import | grep '\*' | grep -v '.mvn' | wc -l
```

**Comment by istraka** [comment]
+1
Checkstyle needs some time to parse java files. Not much in our case tough. IFor now We can stick with @mnovak1 solution for now.

**Comment by fabiobrz** [comment]
> My experience with check style plugin is quite annoying. Thus I would prefer to add check into `.travis.yml`:
> 
> ```
> git grep import | grep '\*' | grep -v '.mvn' | wc -l
> ```
> 
> @jboss-eap-qe/mp-team any thoughts?

Hi @mnovak1, Travis checks are ok for me too.

**Comment by mchoma** [comment]
Problem with travis check is I found problem lately when creating PR on github. It would be better if it tell me also while developing locally.
