### ISSUE TITLE
Migrate RHOAR QE coverage for MicroProfile Open-API

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#11]
Migrate relevant test coverage from 

 - https://github.com/rhoar-qe/thorntail-test-suite/tree/master/microprofile
 - https://github.com/javaee-samples/microprofile1.4-samples

**Comment by fabiobrz** [comment]
See fork https://github.com/fabiobrz/eap-microprofile-test-suite/tree/EAP7-1319

**TODO**
* verify test coverage for v. 1.0 and 1.1
* verify assertions 
* code improvements via refactoring
* dependency management clean organization and optimization 
* keep on running tests against feature branch

**Comment by mnovak1** [comment]
@fabiobrz  hi, can it be marked as done and closed?

**Comment by fabiobrz** [comment]
Hi @mnovak1, sure. Just closing it.
