### ISSUE TITLE
Migrate RHOAR QE coverage for MicroProfile JWT-Auth

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#12]
Migrate relevant test coverage from 

 - https://github.com/rhoar-qe/thorntail-test-suite/tree/master/microprofile
 - https://github.com/javaee-samples/microprofile1.2-samples
 - https://github.com/javaee-samples/microprofile1.4-samples

**Comment by honza-kasik** [comment]
_Note to self:_
Relevant tests are:

- https://github.com/rhoar-qe/thorntail-test-suite/tree/master/microprofile/microprofile-jwt-1.1
- https://github.com/javaee-samples/microprofile1.2-samples/tree/master/jwt-auth
- https://github.com/javaee-samples/microprofile1.4-samples/tree/master/jwt-auth

**Comment by mnovak1** [comment]
@honza-kasik hi, can it be marked as done and closed?

**Comment by honza-kasik** [comment]
@mnovak1 I'll make just one final check today to be double sure everything was done and the I'll close this.

**Comment by mnovak1** [comment]
@honza-kasik   hi, can it be marked as done and closed?

**Comment by honza-kasik** [comment]
@mnovak1 All RHOAR relevant test scenarios are covered already in this testsuite. This can be closed.
