### ISSUE TITLE
Introduce server distribution per maven module when using jboss.home/dist property

### ISSUE THREAD

**Issue by istraka** [jboss-eap-qe/eap-microprofile-test-suite#129]
During test development I have encountered several issues with current pom.xml (discussed here) and arquillian.xml (discussed in https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/131):

### Application server configuration may be changed
`jboss.home` property defines path to a server which tests are executed against. All modules uses same distribution. There are several main issues:
* A bug may change the distribution in unintended way which may be a issue for another module - this may unnecessarily ruin whole test execution
* A tester may have specific test environment (i.e. changes to the distribution are not permitted) which may cause problems (@rhusar had the issue)
* Tester may not notice there is a change in configuration (due to a bug) which may cause complications with test development

It is a common practice to copy a server to a target directory. 

**How?** 
[maven-resources-plugin](https://maven.apache.org/plugins/maven-resources-plugin/) can copy resources without extensive space usage, e.g. `modules` dir (~170M) can be excluded.

With this approach `jboss.home` can no longer be used to define distribution for testing purposes since it should point to the right distribution (the one in a target). Hence I propose `jboss.dist` replaces `jboss.home` system property. **This shall be a change to the API** which is a biggest con.

The destination shall be `target/jboss-as` dir - same as for `download-wildfly` profile.

**Comment by rsvoboda** [comment]
Original issue was covering 2 different topics, arq topic covered in https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/131

**Comment by rsvoboda** [comment]
First I want to add few points to your arguments
 - tests should not produce side-effects, if so we need a way to detect them
 - `bug may change the distribution in unintended way` - we still need to detect this
 - test development is usually tight to one module, so using one instance shouldn't be a problem
Now back to the topic ...

Proposed behavior (server distro per module) is already covered when using `<artifactId>wildfly-dist</artifactId>` way.

We can enhance scenario when wf/eap path is provided by system property. I don't want to change current way with `jboss.home` because it was intended to behave as it is behaving now - just one instance, as mentioned above, tests should not have side effects and they need to clean their mess. If something falls apart it means there is a bug which need attention. On the other hand we can of course have a way to mitigate the chained failures.

And that brings me to `jboss.dist` property. We should have a profile (activated by this property) which takes case or bits distribution similarly to `download-wildfly` profile ++ set's `jboss.home` property.

This brings us to the a problem because that way (using `jboss.dist` property on command line) we would have 2 profiles activated, one taking care of `jboss.dist` way, one downloading and unzipping WF. Unfortunately maven doesn't handle activation by multiple properties :(

So we need to define what would be the default and how would be activated 3 modes we would support implementing this enhancement.

**Comment by istraka** [comment]
I might have omit stressing out an impact on test execution.

> tests should not produce side-effects, if so we need a way to detect them
> `bug may change the distribution in unintended way` - we still need to detect this
I definitely agree, but making test environment for modules less isolated is not the way. If we want to detect such thing in a reliable way, we should introduce a tool that would check the configuration and the state after a module (testing) is finished.

> test development is usually tight to one module, so using one instance shouldn't be a problem
However whole test execution is not. E.g. if there is a change in the model and a setup task needs a change, it should not compromise other modules.

> Proposed behavior (server distro per module) is already covered when using <artifactId>wildfly-dist</artifactId> way
Yes, however we need to test against specific distribution (CD releases) the profile is not applicable. Moreover even during test development we are running against specific branches or pull-requests.

Moreover `jboss.home` may be immutable (yet still product of compiling specific branch/PR). This leads and has already led to problems.

>We can enhance scenario when wf/eap path is provided by system property. I don't want to change current way with jboss.home because it was intended to behave as it is behaving now
What is the reason that all testsuite modules must share one distribution?

**Comment by rsvoboda** [comment]
> What is the reason that all testsuite modules must share one distribution?

No files need to be copied, from test execution perspective I don't see any limitation.

> This leads and has already led to problems.

Please give an example

**Comment by rsvoboda** [comment]
Some thoughts on distro per module solution possibilities

A) Having just jboss.dist property
```
mvn clean install                             => download-wildfly
mvn clean install -Djboss.dist=/path/to/dist  => copy-dist-to-target
```
What will be equivalent for quick compilation via `mvn clean verify -DskipTests -DskipITs -Djboss.home=foo` command we have now ?

B) Keeping both jboss.dist and jboss.home properties
```
mvn clean install                               => WHAT here ?
mvn clean install -Dwf                          => download-wildfly
mvn clean install -Djboss.dist=/path/to/dist    => copy-dist-to-target
mvn clean install -Djboss.home=/path/to/home    => nothing
```
Bad `mvn clean install` experience

**Comment by istraka** [comment]
I see three problems
- possible risk in having a bug in tests that may ruin whole test execution - we should assume there are bugs which may get be visible later. With isolating test environment per test module we still have lots of tests laying in other modules running smoothly.
- distribution is not in clean state if: you create a bug during a test development or you hit ctrl-c during debugging (and cleanup tasks are not executed). Then you need to recover either from backup or manually cleaning the distribution
-  if your distribution is immutable (due to reasons) you need to deal with copying and investigating why a stuff is not working:
```
org.jboss.as.arquillian.container.ServerSetupObserver$ServerSetupTaskHolder setup
ERROR: Setup failed during setup. Offending class 'org.jboss.eap.qe.microprofile.metrics.integration.ft.SetupTask@2ce6c6ec'
java.lang.IllegalStateException: Writing test modules in jboss.home directory /Users/rhusar/git/wildfly/dist/target/wildfly-19.0.0.Beta1-SNAPSHOT is not allowed
```

Keeping jboss.dist and jboss.home (`B)`) makes no sense.

>What will be equivalent for quick compilation via mvn clean verify -DskipTests -DskipITs -Djboss.home=foo command we have now ?

The very same command: `mvn clean verify -DskipTests -DskipITs -Djboss.home=foo `. The plugin does not require the path to exists:
```
mvn clean verify  -Djboss.dist=foo -DskipTests
...
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (ts.copy-wildfly) @ microprofile-jwt-auth-tool ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/istraka/repositories/istraka/eap-microprofile-test-suite/microprofile-jwt-auth-tool/foo
```

**Comment by rsvoboda** [comment]
Good discussion, now I'm convinced, let's proceed with `jboss.dist` approach ;)

**Comment by rhusar** [comment]
I haven't really read this in detail, but copying the specified distribution to `target/` is the simplest way that makes any sense which we have been doing for a very long time and is the standard way to do this so the fix appears to do this right – good job!
