### ISSUE TITLE
Migrate RHOAR QE coverage for MicroProfile Fault-Tolerance

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#13]
Migrate relevant test coverage from 

 - https://github.com/rhoar-qe/thorntail-test-suite/tree/master/microprofile
 - https://github.com/javaee-samples/microprofile1.2-samples
 - https://github.com/thorntail-examples/circuit-breaker

**Comment by mnovak1** [comment]
Work on this is WIP - see branch:
https://github.com/mnovak1/eap-microprofile-test-suite/tree/EAP7-1347

TODOs:
- try migrated tests from https://github.com/rhoar-qe/thorntail-test-suite/tree/master/microprofile with initial MP FT integration into Wildfly (once it's delivered https://issues.jboss.org/browse/WFLY-12590)
- clean poms (use dependency management, inherit from parent)
- migrate all tests from https://github.com/javaee-samples/microprofile1.2-samples
- migrate all tests from https://github.com/thorntail-examples/circuit-breaker

**Comment by mnovak1** [comment]
PR with tests: https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/175

Closing
