### ISSUE TITLE
arquillian.xml is not configurable

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#131]
### arquillian.xml is not configurable
`arquillian.xml` file should be configurable via system properties. This will help us with:
- A tester can easily change a configuration without modifying the file
- Another step to an easy property based testing
- Easy way to change arquillian configuration on Jenkins if needed

split of https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/129

**Comment by rsvoboda** [comment]
We can of course parametrize it, but do we really need it now ?

@istraka what's the current need you want to address ?

**Comment by mnovak1** [comment]
Actually Arquillian already allows to change `arquillian.xml` using system property:
```mvn .. -Darquillian.xml=$PWD/Darquillian-custom.xml```

**Comment by mnovak1** [comment]
Closing
