### ISSUE TITLE
REST Assured - baseUri with fully-qualified address vs. baseUri + port + basePath

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#140]
REST Assured - `baseUri` with fully-qualified address vs. `baseUri` + `port` + `basePath`

This topic was brought up by @istraka as part of https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/126 review.

```patch
-                .baseUri("http://" + managementClient.getMgmtAddress())
-                .port(managementClient.getMgmtPort())
-                .basePath("metrics")
+                .baseUri(metricsURL)
```

@jboss-eap-qe/mp-team we should agree on preferred approach.

Googling some code examples I think `baseUri` with fully-qualified address is more common case.

**Comment by mnovak1** [comment]
+1 for baseUri

**Comment by mnovak1** [comment]
@fabiobrz baseUri with fully-qualified address
