### ISSUE TITLE
MicroProfileJwtSubsystemTestCase - @Before used instead of @After ?

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#151]
I think in MicroProfileJwtSubsystemTestCase `@Before` is used instead of `@After`
https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/microprofile-jwt/src/test/java/org/jboss/eap/qe/microprofile/jwt/MicroProfileJwtSubsystemTestCase.java#L49

Is it intended to run `before()` and `after()` for each test or it's intended to run just once for the class ?

**Comment by honza-kasik** [comment]
Yes, it is intended. Otherwise we'd have to be sure that each tests (which will be maybe added in future) will clean up after itself.

**Comment by honza-kasik** [comment]
Oh, I see it now... Thanks for spotting this, will fix!

**Comment by rsvoboda** [comment]
ok, anyway I think you still need to change one Before to After
