### ISSUE TITLE
OnlineManagementClient not closed in several cases

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#152]
OnlineManagementClient not closed in `new Administration(ManagementClientProvider .onlineStandalone()).reload();` cases

```
git grep "ManagementClientProvider.onlineStandalone()).reload"
microprofile-metrics/src/test/java/org/jboss/eap/qe/microprofile/metrics/integration/config/CustomMetricBaseTest.java:        new Administration(ManagementClientProvider.onlineStandalone()).reload();
microprofile-metrics/src/test/java/org/jboss/eap/qe/microprofile/metrics/integration/config/CustomMetricModelFilePropsTest.java:        new Administration(ManagementClientProvider.onlineStandalone()).reload();
microprofile-metrics/src/test/java/org/jboss/eap/qe/microprofile/metrics/integration/config/CustomMetricModelPropsTest.java:        new Administration(ManagementClientProvider.onlineStandalone()).reload();
microprofile-metrics/src/test/java/org/jboss/eap/qe/microprofile/metrics/integration/config/CustomMetricSystemPropertyTest.java:        new Administration(ManagementClientProvider.onlineStandalone()).reload();
microprofile-metrics/src/test/java/org/jboss/eap/qe/microprofile/metrics/integration/ft/FTMetricTest.java:        new Administration(ManagementClientProvider.onlineStandalone()).reload();
```

@jboss-eap-qe/mp-team

**Comment by fabiobrz** [comment]
Hi @rsvoboda, I see that OpenAPI module is not mentioned here which is fine, but I'd like to know your opinion about what has been done there in order to get an `OnlineManagementClient` instance wrapping a `ModelControllerClient` obtained from ARQ provided `ManagementClient` (see for instance https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/microprofile-open-api/src/test/java/org/jboss/eap/qe/microprofile/openapi/advanced/AcceptHeadersAndFormatParameterInteractionTest.java#L68).

In this very case - i.e. for all OpenAPI module test classes - the `OnlineManagementClient::close` method is *never* called, because it would close the underlying connection held by ARQ ManagementClient, which seems to be a single instance.

WDYT?

**Comment by rsvoboda** [comment]
I don't believe we need to explicitly close injected ManagementClient instance.

**Comment by fabiobrz** [comment]
Thank you @rsvoboda, that's the confirmation I was asking for. I asked @mnovak1 too so I am fine with that now.

**Comment by mnovak1** [comment]
Let's either use 
`new Administration(ManagementClientProvider.onlineStandalone(managementClient)).reload();`
so OnlineManagement client does not need to be closed or use our API and get rid of managementClient - change:
```
@Before
    public void before() throws ConfigurationException, InterruptedException, TimeoutException, IOException {
        metricsURL = "http://" + managementClient.getMgmtAddress() + ":" + managementClient.getMgmtPort() + "/metrics";
        new Administration(ManagementClientProvider.onlineStandalone()).reload();
    }
```
to
```
    @Before
    public void before() throws ConfigurationException, InterruptedException, TimeoutException, IOException {
        ArquillianContainerProperties arqProps = new ArquillianContainerProperties(
                ArquillianDescriptorWrapper.getArquillianDescriptor());        
        metricsURL = "http://" + arqProps.getDefaultManagementAddress() + ":" + arqProps.getDefaultManagementPort() + "/metrics";
        try (OnlineManagementClient client = ManagementClientProvider.onlineStandalone(arqProps))   {
            new Administration(client).reload();
        }
    }
```
wdyt?

**Comment by fabiobrz** [comment]
Hi @mnovak1. Maybe it's just because that is how I am doing it in my test classes but... I like it. +1 for  me.

**Comment by mnovak1** [comment]
Because there is issue with wrapped management client https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/169 the first option is no way. 

Let's got the 2nd way:
```
@Before
    public void before() throws ConfigurationException, InterruptedException, TimeoutException, IOException {
        ArquillianContainerProperties arqProps = new ArquillianContainerProperties(
                ArquillianDescriptorWrapper.getArquillianDescriptor());        
        metricsURL = "http://" + arqProps.getDefaultManagementAddress() + ":" + arqProps.getDefaultManagementPort() + "/metrics";
        try (OnlineManagementClient client = ManagementClientProvider.onlineStandalone(arqProps))   {
            new Administration(client).reload();
        }
    }
```

**Comment by mnovak1** [comment]
https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/180 merged

Closing
