### ISSUE TITLE
Enforce common codestyle

### ISSUE THREAD

**Issue by honza-kasik** [jboss-eap-qe/eap-microprofile-test-suite#16]
When adding tests we should enforce uniform code style.

**Comment by rsvoboda** [comment]
Do you suggest any particular checkstyle rule-set ?

**Comment by honza-kasik** [comment]
I personally prefer Google Java code style https://google.github.io/styleguide/javaguide.html

**Comment by rsvoboda** [comment]
TBH I would keep the same checkstyle as WildFly, mainly for consistency reasons.

**Comment by honza-kasik** [comment]
+1 That makes more sense.

**Comment by mnovak1** [comment]
I'm ok with WF approach as well. 

Just to confirm, those are the correct formatters,right? - https://github.com/wildfly/wildfly-core/tree/master/ide-configs

**Comment by rsvoboda** [comment]
I was talking about this: https://github.com/wildfly/wildfly-core/blob/master/pom.xml#L339

I think IDE configs might be a bit outdated, would stick with IntelliJ Idea defaults

**Comment by rsvoboda** [comment]
@honza-kasik can we consider `format` profile as solution for this issue ?
https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/pom.xml#L249

**Comment by mnovak1** [comment]
afaict this issue is solved by using formatter-plugin and adding as check into PR template. Closing
