### ISSUE TITLE
Prepare daily CI for WF master and eap-microprofile-test-suite execution

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#165]
Prepare daily CI for WF master and eap-microprofile-test-suite execution

There is for example ServerContextRootTest#testExpectedServerInformationInOpenApiDoc fail with WF master

Automated job needs to be in place to check these things asap.
@mnovak1 fyi

**Comment by istraka** [comment]
We are on board already, aren't we?
https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/EAP7/view/EAP7-Microprofile/job/eap-7.x-microprofile-testing-pipeline/104/

**Comment by rsvoboda** [comment]
Ah, didn't know about it.

 - who reviews the results ?
 - TS is executed in "limited" scope ... for example MP OpenAPI tests are not covered by nightly runs

**Comment by istraka** [comment]
> who reviews the results ?

Noone yet, I guess.

> TS is executed in "limited" scope ... for example MP OpenAPI tests are not covered by nightly runs

Once everything is merged (WF PRs) these modules should be included, shouldn't they?

**Comment by mnovak1** [comment]
@jboss-eap-qe/mp-team  any volunteer for this issue?

**Comment by mnovak1** [comment]
I'll take this one as it depends on https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/166. I'll check else is missing here.

**Comment by mnovak1** [comment]
As https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/166 is done I've triggered rebuild on latest WF CI run:
https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/eap-7.x-microprofile-testsuite/82/

If it passes this one can be closed.

**Comment by mnovak1** [comment]
Job passed, closing.
