### ISSUE TITLE
Enable MP OpenAPI and MP JWT modules once specs merged in master and WF has new release available

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#166]
Enable MP OpenAPI and MP JWT modules once specs merged in master and WF has new release available

https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/pom.xml#L299

Placeholder for future action

**Comment by mnovak1** [comment]
@fabiobrz @honza-kasik I believe MP OpenAPI and MP JWT is already merged, right? 

This is related also to MP FT which can be enabled as well.

**Comment by honza-kasik** [comment]
@mnovak1 Indeed it is https://github.com/wildfly/wildfly/pull/12853

**Comment by fabiobrz** [comment]
Hi @mnovak1. Yes, MP OpenAPI PR was merged, see https://github.com/wildfly/wildfly/pull/12852

**Comment by fabiobrz** [comment]
Sure, thanks @mnovak1.

**Comment by mnovak1** [comment]
Fixed by https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/182 

Closing
