### ISSUE TITLE
Evaluate CI options for the project

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#17]
Evaluate CI options for the project

Consider 2 main use-cases
 - Released WildFly versions
 - WildFly master based release

**Comment by mnovak1** [comment]
@jboss-eap-qe/mp-team any volunteer for this issue?

**Comment by mnovak1** [comment]
Well, closing this one as it duplicates https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/165
