### ISSUE TITLE
Prepare Microprofile pipeline to run with one-offs

### ISSUE THREAD

**Issue by mnovak1** [jboss-eap-qe/eap-microprofile-test-suite#177]
Prepare Microprofile pipeline to be able to be executed with one-offs.

**Comment by fabiobrz** [comment]
Hi @mnovak1, changes for this were merged, see https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-eap/tests-jobs/merge_requests/1213.

**Comment by mnovak1** [comment]
@fabiobrz thanks, closing
