### ISSUE TITLE
Fix Microprofile pipeline to run with face jobs

### ISSUE THREAD

**Issue by mnovak1** [jboss-eap-qe/eap-microprofile-test-suite#178]
Pipeline is currently broken [1] and need to fix it to be able to run with custom Wildfly builds. 

[1] https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/eap-7.x-microprofile-custom-build-from-sources-face/

**Comment by fabiobrz** [comment]
Last run of [1], mentioned in original post is green.

A new job was added to handle testing against custom builds, see [2].

[1]
https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/eap-7.x-microprofile-custom-build-from-sources-face/88/

[2]
https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/EAP7/view/EAP7-Microprofile/job/eap-7.x-microprofile-custom-build-from-url-face/7/

**Comment by mnovak1** [comment]
@fabiobrz thanks!
