### ISSUE TITLE
Consolidate face jobs

### ISSUE THREAD

**Issue by mnovak1** [jboss-eap-qe/eap-microprofile-test-suite#197]
Face jobs: we have:

1. -  for custom build from sources - compliant with common practices for CI face jobs - i.e. flow/components/allows reporting data to specific version through REPORTED_VERSION param https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/eap-7.x-microprofile-custom-build-from-sources-face
2. -  for custom build from URL - compliant with common practices for CI face jobs - i.e. flow/components/allows reporting data to specific version through REPORTED_VERSION param https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/EAP7/view/EAP7-Microprofile/job/eap-7.x-microprofile-custom-build-from-url-face/
3. -  for one-off testing https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/EAP7/view/EAP7-Microprofile/job/eap-7.x-microprofile-one-off-face/
4. -  “simple” job - simple here means simple and useful input interface which can satisfy different use cases but - for instance - misses the REPORTED_VERSION https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/eap-7.x-microprofile-simple-face/

After discussion following action will be taken:
2) and 4) are actually overlapping at the moment. -> merge 2,4-> result will be 1, 3 and merge 2,4

**Comment by fabiobrz** [comment]
Solved by https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-eap/tests-jobs/merge_requests/1229.
Issue can be closed.

**Comment by mnovak1** [comment]
@fabiobrz thanks, closing
