### ISSUE TITLE
Usage of hamcrest in combination with com.google.gson.JsonArray

### ISSUE THREAD

**Issue by zhantemirov** [jboss-eap-qe/eap-microprofile-test-suite#203]
During the test review there was a suggestion to use `hamcrest AssertThat` assertions and get rid of unnecessary `AssertJ` dependency.

But there is an issue I met with. At the moment I have no idea how to make `Java8 Stream`, `com.google.gson.JsonArray` and `AssertThat(Matcher matcher)` work together. 

The first problem - I don't know how to apply a Java lambda function like `anyMatch` on `JsonArray` [1] instance which has only an `Iterator`. 

The second problem is that the vanilla `Hamcrest` does not support lambda - at least such a complex construction with few lines and return statement.

More details are at row [2].

[1] - https://www.javadoc.io/doc/com.google.code.gson/gson/2.6.2/com/google/gson/JsonArray.html

[2] - https://github.com/zhantemirov/eap-microprofile-test-suite/commit/f5ba3454fc30ed2c6729c72fb231a6bcf9af7311#diff-8772e60c47d343d4963a64945b118fa5R100

Maybe someone has more experience with `Hamcrest` than me and is willing to help?

@mnovak1 @fabiobrz @istraka @honza-kasik 

Related PR - https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/199

**Comment by honza-kasik** [comment]
Ad. `anyMatch` + JsonArray:

Have you looked at http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/Matchers.html#hasItem(org.hamcrest.Matcher) ?

**Comment by zhantemirov** [comment]
@mnovak1 I would like to ask some questions as Honza is not available at the moment.

A construction 

```
assertThat(spans, hasItem(anyOf(condition1, condition2)))
```
should work only in case we compare simple data types. With the complex ones (as `spans` which is JsonArray) we should transform [1] our entry span in order to check the presence of required attributes. Whereas the idea suggested by Honza is good enough - I'm afraid it's not applicable in our case.

In order not to reinvent something that is already done and at the same moment not to add an extra dependency to our project - what kind of decision should be done? 

[1] - https://github.com/zhantemirov/eap-microprofile-test-suite/commit/f5ba3454fc30ed2c6729c72fb231a6bcf9af7311#diff-8772e60c47d343d4963a64945b118fa5R101

**Comment by mnovak1** [comment]
@zhantemirov I did some googling and I think for this case could be used LambdaMatcher: https://gist.github.com/GuiSim/e1d1cde0ab66302ae45c

You can add custom matcher.

**Comment by zhantemirov** [comment]
@mnovak1 I've already seen this, thanks. So where should I put this helper class - would it be suitable to have it in microprofile-opentracing module or in some more general *-util package?

**Comment by mnovak1** [comment]
@zhantemirov I think It can be placed in the module with your test.

**Comment by zhantemirov** [comment]
@mnovak1 all custom matcher need to have the input argument as Object class for successful matching. Even though JsonArray (as all classes in Java) extends parent Object class, a JsonArray instance cannot be applied as lambda function.

We can discuss this issue in person and share our thought here afterwards.

**Comment by zhantemirov** [comment]
Resolved by using a construction [1] like:

```
JsonArray spans = trace.getAsJsonArray("spans");

List<JsonElement> spanList = new ArrayList<>();
spans.forEach(spanList::add);

assertThat(spanList.stream().anyMatch(condifition), is(true))
```

[1] - https://github.com/zhantemirov/eap-microprofile-test-suite/blob/migrate-open-tracing/microprofile-opentracing/src/test/java/org/jboss/eap/qe/microprofile/opentracing/v10/MicroProfileOpenTracing10Test.java#L108
