### ISSUE TITLE
Evaluate common logging tool 

### ISSUE THREAD

**Issue by mnovak1** [jboss-eap-qe/eap-microprofile-test-suite#21]
Based on discussion in PR https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/20 , there is need to log output from started docker container (at least debug purposes). Currently it's logged to standard output using `System.out` which makes standard log messy and hard to read. Also there might be need to log information from test itself for debug purposes.

Current suggestions: 
Use one of the Lombok (https://projectlombok.org/features/log) annotations, for example `@Log4j` or  @Slf4j 

It should be considered whether logs can be send into Logstash.

Any suggestions/comments/thoughts/preferences?

**Comment by zhantemirov** [comment]
Since I am not so experienced in using different implementations of logger - I'm used to @Log4j or Vanilla one. Hope this helps. 

Let's wait for more descriptive and useful inputs from team members :)

**Comment by rsvoboda** [comment]
I guess `org.jboss.logging:jboss-logging` should be the first solution to consider as it's used in WF/EAP.

Another concern I have is why do we need to use logging.
Exceptions / assertions are the way to communicate.

Log messages mean manual intervention to review log file.

**Comment by mnovak1** [comment]
> Another concern I have is why do we need to use logging.
> Exceptions / assertions are the way to communicate.

It helps to investigate failures and especially intermittent test failures as those are not possible to debug using debugger. Debug logs show progress of the test and can direct to root cause without spending too much time on investigation. They also provide data for creating issue and are valuable information for developer fixing the issue.

**Comment by rsvoboda** [comment]
This seems to be relevant for logging on server+application side.

But on test side why do we need logging? We should try to avoid that and replace it with assertions so there is very limited need for manual intervention (review of the logs).

**Comment by mnovak1** [comment]
Assertions provide information that something went wrong but usually such assertion is at the end of the test. Usually there are not assertions for everything the test is doing and even if there are it might be unclear what happened. It might be test/env issue (for example docker container did not start or other issue with environment). In case there are logs just from application server there might be still unclear in which phase of test caused them. Debug logs from test would allow to pinpoint/narrow problematic test operation using timestamps.

**Comment by rsvoboda** [comment]
It all depends how you structure your tests.

Assertions should not be just at the end, they should be scattered within the test method.
Test methods should be small. If you don't want to fail the test on the first failed assertion you have techniques to do so - e.g. JUnitSoftAssertions.
If the test is not doing "fail fast" approach you need to make sure it will fail in reasonable time - e.g. connection / read timeouts.

Some resources (I googled now) to check _for inspiration_:
 - https://phauer.com/2019/modern-best-practices-testing-java/
 - https://www.baeldung.com/junit-assertions
 - https://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html

Now about the above comment:

> Assertions provide information that something went wrong but usually such assertion is at the end of the test. Usually there are not assertions for everything the test is doing and even if there are it might be unclear what happened. 

See above, test structure needs to change, we can't invest in review of logs for tests, tests needs to be robust.

> It might be test/env issue (for example docker container did not start or other issue with environment). 

There should be exception and it translates to test fail

> In case there are logs just from application server there might be still unclear in which phase of test caused them. 

Not true if you have assertions scattered within the test code

> Debug logs from test would allow to pinpoint/narrow problematic test operation using timestamps.

Which of MP specs would need to log such level of details in regular testing execution? I need an example.

**Comment by mnovak1** [comment]
We had discussion with @rsvoboda and decided not to add any logging at this moment and follow principles mentioned in [1]. This might be re-evaluated in the future once strong need arises but preferred way will be that tests for MP specs should be kept simple enough (KISS principle) or refactored to avoid it.

[1] https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/21#issuecomment-551700495
