### ISSUE TITLE
Evaluate recommended approach of structuring tests into modules

### ISSUE THREAD

**Issue by mnovak1** [jboss-eap-qe/eap-microprofile-test-suite#22]
Goal of this issue is to discuss how tests will be divided into modules in the test suite and provide recommended approach.

When migrating tests from other test suites (mainly from TT QE test suite) or writing new tests, does it make sense to respect the module structure, for example as in https://github.com/rhoar-qe/thorntail-test-suite/tree/master/microprofile or to place all the tests for given MP spec into single module.

Possible approaches:

**Group all tests for given MP spec into single module - THIS IS THE RECOMMENDED APPROACH** :
* for example to group all tests for MP Metric together
* in case that tests for integration of multiple MP specs are developed and it's not clear to which module they belong then new module can be created. Preferable such module should container name of used MP specs.

**Group tests for given MP spec into multiple modules based on MP spec version** (same approach as in  https://github.com/rhoar-qe/thorntail-test-suite/tree/master/microprofile)

Suggest other approaches/thoughts?

**Comment by mnovak1** [comment]
_Group all tests for given MP spec into single module_  approach appears to make more sense to use. 

It provides better view of structure and where to look/place tests for given MP spec (like group all tests for MP Metric to single module). 

In case that test includes integration of multiple MP specs/testing high level scenario then separate module with proper name should be created.

**Comment by fabiobrz** [comment]
Hi @mnovak1, so you're suggesting to refactor and add a new module for MP spec/version?

**Comment by mnovak1** [comment]
@fabiobrz Just new for each MP spec (not version). So for example all MP OpenAPI tests would be in single module. 
But in case that test will cover scenario with more MP specs then new module with proper name should be created.

**Comment by fabiobrz** [comment]
Ok @mnovak1, let's see if we can arrange it. Do you have a fork for it?

**Comment by mnovak1** [comment]
@fabiobrz I've created `microprofile-fault-tolerance` module for tests for MP FT:
https://github.com/mnovak1/eap-microprofile-test-suite/tree/EAP7-1347

**Comment by mnovak1** [comment]
I'll close this issue as basic structure was chosen (I've updated first comment):
RECOMMENDED APPROACH is:
* **Group all tests for given MP spec into single module**
