### ISSUE TITLE
Verify whether FT tests involving EAR + FT Metrics and based on old Hystrix behavior should be removed 

### ISSUE THREAD

**Issue by fabiobrz** [jboss-eap-qe/eap-microprofile-test-suite#238]
There's one test which is supposed to verify the behavior of FT Metrics when in a scenario that involves an EAR with two identical sub-deployments.
MicroProfile specs are not supporting multiple deployments, which makes sense in most common microservices/cloud-native scenarios, so the behavior of such a configuration depends on the vendor implementation.

This has also been discussed in a JIRA involving MP Health subsystem, see 
https://issues.redhat.com/browse/WFLY-12835?focusedCommentId=14115173&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14115173

so WildFly still doesn't support the above mentioned configuration and the test [testFaultToleranceMetricsAreSummedWithSameDeployments](https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/microprofile-fault-tolerance/src/test/java/org/jboss/eap/qe/microprofile/fault/tolerance/MultipleFaultToleranceModuleEarTest.java#L98) `@Ignore` clause should be changed to reference WFLY-12835 or the test should be removed altogether.

Regarding the [testFirstModuleConfigureHystrix](https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/microprofile-fault-tolerance/src/test/java/org/jboss/eap/qe/microprofile/fault/tolerance/MultipleFaultToleranceModuleEarTest.java#L124) test, this should be removed altogether because depending on assumptions which are only related to Hystrix.

@mnovak1 WDYT?

**Comment by mnovak1** [comment]
Hi @fabiobrz, 

thanks for looking at it. I think that `@Ignore` annotation in https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/microprofile-fault-tolerance/src/test/java/org/jboss/eap/qe/microprofile/fault/tolerance/MultipleFaultToleranceModuleEarTest.java#L98 can be changed to WFLY-12835. I would just keep the test for reference.

https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/microprofile-fault-tolerance/src/test/java/org/jboss/eap/qe/microprofile/fault/tolerance/MultipleFaultToleranceModuleEarTest.java#L124  can be removed.

**Comment by fabiobrz** [comment]
Thanks @mnovak1 - I assigned the issue to myself so that I can provide an update shortly.

**Comment by fabiobrz** [comment]
Hi @mnovak1 - shouldn't this one be closed since https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/239 has been merged?

**Comment by fabiobrz** [comment]
Closing as resolved via https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/239
