### ISSUE TITLE
Replace the no longer available `undertow-legacy-security` layer 

### ISSUE THREAD

**Issue by fabiobrz** [jboss-eap-qe/eap-microprofile-test-suite#251]
The MicroProfile TS executes some Bootable JAR tests. Some of such tests' layers configuration still defines `undertow-legacy-https` as part of the server configuration, athough this layer has been removed since WildFly 25.

At the moment, this wil be worked around temporarily by bumping the default (i.e. POM property) WildFly Galleon Pack version to the latest supporting such layer, that is to say WildFly `24.0.0.Final`. BTW, this will allow for a more recent - and JDK 17 compliant - version of the `wildfly-jar-maven-plugin` to be used.

This issue is to track the effort needed to adjust the Bootable JARs layers configuration in order to be compliant with newer WidFly and EAP releases (e.g.: using undertow-https and chenging the CLI commands to configure the runtime?).

**Comment by jbliznak** [comment]
most of this resolved in https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/256

But we still need to revert this workaround https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/pom.xml#L68 introduced in https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/253

**Comment by fabiobrz** [comment]
> most of this resolved in #256

Great, thanks for tracking it, @jbliznak 

> But we still need to revert this workaround https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/pom.xml#L68 introduced in #253

As discussed already, the above mentioned change was wrong, being https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/89ba0e129b6c6f5710b5721ed669676e46ff9dc4/pom.xml#L68 the right one instead.

That being said, this one is outdated now, see https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/pom.xml#L79 - so the above remarks are not relevant anymore and the issue can be closed as fixed.
