### ISSUE TITLE
Bump Arquillian, wildfly-arquillian to 5.0.0.Alpha2

### ISSUE THREAD

**Issue by fabiobrz** [jboss-eap-qe/eap-microprofile-test-suite#252]
The MicroProfile TS still uses Arquillian 1.5.0 and WildFly Arquillian 3.01.
This one still works with ongoing changes for JDK17 but such dependencies version should be bumped to newer ones in the short term.

This issue is for tracking the required effort.

* A _potential_ starting point: https://github.com/fabiobrz/eap-microprofile-test-suite/commits/WIP-jdk17-support.bump-arquillian

**Comment by jbliznak** [comment]
solved in https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/256/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R42 - upgraded to 5.0.0.Alpha5
