### ISSUE TITLE
Evaluate tooling for configuring WF/EAP server

### ISSUE THREAD

**Issue by mnovak1** [jboss-eap-qe/eap-microprofile-test-suite#26]
Purpose of this issue is to discuss tooling for configuring WF/EAP server. 

As most of the configuration for MicroProfile are configured using MP Config, it's expected that most of the configuration will done using deployed application using microprofile-config.properties. However there are cases when configuring server model is needed. 

Goal is to find the right tool for configuring model. There is number of options:
* **THIS IS CHOSEN OPTION** - Use creaper [1] project (creaper core) which might be too "big gun" for our needs.
* Use Java API provided for WF/EAP directly
* Use CLI commands converted to Java API
* Rest API

Using creaper library would be simplest but has disadvantage that currently there is no maintainer. Other options are closer to customer use but are laborious so it will depend on how many things we need to configure. 

Could you provide examples of configuration needed for tests in your specification, please?

[1] https://github.com/wildfly-extras/creaper/

**Comment by rsvoboda** [comment]
I prefer these 2 ways

 - Creaper core
 - CLI commands converted to Java API (if there is tooling / helper classes for this)

**Comment by honza-kasik** [comment]
I would go Creaper way. In my opinion it won't die so easily even when it doesn't have any maintainer because it's used among other projects (testsuites) too much.

**Comment by fabiobrz** [comment]
Hi @mnovak1 
 the tests which are supposed to involve Wildfly/EAP server model configuration are not so relevant at least for the MP OpenAPI feature, as the management model will be empty.
That said if general server model is to be configured for - let's say - integration tests to work, then it will be basic configuration (e.g.: at least regarding MP OpenAPI cit could be a call to enable MP Metrics subsystem?), and that would be the reason why I'd agree with @rsvoboda suggested, i.e. using Creaper core.

What @honza-kasik says makes sense to me as well, although my concern would be if the project is too outdated.

**Comment by mnovak1** [comment]
@fabiobrz @honza-kasik thanks guys for feedback. 

For MP FT there is need to "enable" it in model (add extension/subsystem) and reload. Otherwise MP FT subsystem is empty. So creaper core is good choice for me in case that "it just works". If not then CLI commands converted to Java API is 2nd preferred way from my pov.

**Comment by mnovak1** [comment]
Based on discussion above decision is to **use Creaper core**.
