### ISSUE TITLE
Disable the health default procedures

### ISSUE THREAD

**Issue by nicolasduminil** [jboss-eap-qe/eap-microprofile-test-suite#263]
Disabling the health default procedures by using the `DisableDefaultHealthProceduresSetupTask` class seems to be way too complicated. The MP Configuration specs mentions that this also could be done by setting the `mp.health.disable-default-procedures` property to true in the `microprofile-config.properties` file.
I tried that but it didn't work. 
Also, I can see that the class `MultiDeploymentHealthTest` tries to disable the health default procedures as follows:

        @Deployment(name = "deployment1", order = 1, testable = false)
        public static Archive<?> deployment1() {
          return ShrinkWrap.create(WebArchive.class, MultiDeploymentHealthTest.class.getSimpleName() + "-1.war")
                ...
                .addAsManifestResource(new StringAsset("mp.health.disable-default-procedures=true"),
                        "microprofile-config.properties")
                ...
        }

However, it still has the following annotation:

    @ServerSetup({ DisableDefaultHealthProceduresSetupTask.class })

which duplicates the same functionality. Commenting out the annotation above, the Arquillian tests are failing, showing that only setting the property in the deployment method isn't enough.

So, I have the following questions:
  - is it possible to disable the health default procedures by setting the associated property in `microprofile-config.properties` and, if yes, why doesn't it work here ?
  - is it possible to do it by setting the associated property in the deployment method, as shown above and, if yes, why doesn't it work here and why did you need to annotate with `@ServerSetup` ?
  - is there any simpler way to do it ?

Many thanks in advance.

Kind regards,

Nicolas

**Comment by fabiobrz** [comment]
Hi @nicolasduminil, thanks for your feedback and sorry for the late reply.
We've been looking into the issue and gathered enough information to log https://issues.redhat.com/browse/WFLY-19147. 

We'll update tests in here based on the outcome of the discussion around the proposed solutions.
