### ISSUE TITLE
Tagging and branching strategy

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#36]
We should define tagging and branching strategy 

**Here is initial proposal for tagging:**
When:
 - Tag new major version when new WF major is released and covers new MP related features

How:
 - Use https://maven.apache.org/maven-release/maven-release-plugin/

Naming:
 - Same as WildFly version (what if there is WF release without MP related feature ?)
 - Start with 1.0.0.Final (we can have CR1/CR2)
 - Start with 1.0.0

**Here is initial proposal for branching:**
 - No branches unless really needed, tags should be enough
 - If branch is needed its name will be $MAJOR.$MINOR, e.g. 1.0 for 1.0.z releases

**Comment by rsvoboda** [comment]
@istraka any progress on this ?

**Comment by istraka** [comment]
@rsvoboda not yet.

**Comment by istraka** [comment]
@rsvoboda is there any public maven repository which we can push artifacts to?

**Comment by rsvoboda** [comment]
maven central, jboss nexus, sonatype nexus

**Comment by istraka** [comment]
Do you know one we have already access to? https://repository.jboss.org/nexus/content/repositories/releases/ looks good (full list: https://repository.jboss.org/nexus/#view-repositories)

**Comment by istraka** [comment]
Agreed on not publishing artifact to a maven repository so far.

I am in favor of starting with `1.0.0.Final` and proposed tagging strategy. Branching proposal looks good to me.
