### ISSUE TITLE
Update Jenkins job and face to be compliant with messages

### ISSUE THREAD

**Issue by honza-kasik** [jboss-eap-qe/eap-microprofile-test-suite#63]
## Problems

* When face job is run, pipeline won't trigger any tests jobs. This is caused by a fact that no job contains sub string of suite name.
* Repository and revision passed in testing metadata are not taken into the account because the pipeline job will evaluate only proprietary parameters instead of default `TESTSUITE_REPO` and `TESTSUITE_REVISION`.

## Solution

We have to options:

### Hack pipeline job so it extracts values from `testingMetadata`

Obtain repo url and revision by

```groovy
def repo = testingMetadata?.components?.'xxx'?.repo ?: ''
def revision = testingMetadata?.components?.'yyy'?.revision ?: ''
```

+ remove filtering based on suite name

### Edit face and Microprofile component in ci-infrastructure-lib

1. Add `TESTSUITE_REPO` and `TESTSUITE_REVISION` parameters to test job
1. 
```patch
--- a/src/org/jboss/qe/pipeline/component/Microprofile.groovy
+++ b/src/org/jboss/qe/pipeline/component/Microprofile.groovy
@@ -9,7 +9,7 @@ class Microprofile extends Component {
     // component name
     private static final String NAME = 'microprofile'
     // suites IDs
-    private static final String MICROPROFILE_SUITE_ID = 'microprofile-testsuite'
+    private static final String MICROPROFILE_SUITE_ID = 'microprofile-tests'
 
     Microprofile(Collection<Suite> suites = [], CustomData customData = new CustomData(), Collection<String> includeJobs = [],
             Collection<String> excludeJobs = [], Scope scope = null, String platforms = null, Collection<Bits> bits = []) {
```

@istraka @fabiobrz @zhantemirov @mnovak1 @rsvoboda WDYT?

**Comment by istraka** [comment]
I am working on the test job. I can rename it to prefix_microprofile-testsuite. It will be compliant solution. Doing this I can change repo and revision parameters to `TESTSUITE_REPO` and `TESTSUITE_REVISION`. Lets finish this hell already.

**Comment by istraka** [comment]
fixed by https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-eap/tests-jobs/merge_requests/1120
