### ISSUE TITLE
Document usage of Jenkinsfile into README.MD

### ISSUE THREAD

**Issue by mnovak1** [jboss-eap-qe/eap-microprofile-test-suite#69]
Document how to setup pipeline on local Jenkins using Jenkinsfile [1]

[1] https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/64/files

**Comment by rsvoboda** [comment]
Any update on this ?

**Comment by mnovak1** [comment]
**How to run microprofile test suite on Jenkins instance using Jenkinsfile:**

- Follow instructions on (https://jenkins.io/doc/book/installing/) to install and run Jenkins 
- Install "Pipeline" and "AnsiColor" plugins - see https://jenkins.io/doc/book/managing/plugins/ for more details
- Create new "pipeline" job ("New Item" -> Choose "Pipeline" option and enter job name "microprofile-test-suite")
- Copy content of Jenkinsfile into _Pipeline script_ section and "Save"
-- Change "linux" label in "agent { label 'linux' }" to contain label assigned to your slaves
-- Change "java-1.8.0-oracle" in "jdk 'java-1.8.0-oracle'" to installed JDK label 
- Trigger build by "Build Now" button - NOTE FIRST WILL FAIL DUE TO ISSUES https://issues.jenkins-ci.org/browse/JENKINS-40574/https://issues.jenkins-ci.org/browse/JENKINS-41929 but all the subsequent runs will work

**Comment by rsvoboda** [comment]
Thanks, I think this could go into README.md file. wdyt ?

**Comment by mnovak1** [comment]
+1, I'll leave on you if you want to make it part of your PR or adding it in follow-up PR (I can do that but I'd like PR [1] to be merged first so I don't have to guess link to Jenkinsfile).

[1] https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/64/

**Comment by rsvoboda** [comment]
I prefer new PR, I will merge #64 now

**Comment by rsvoboda** [comment]
@mnovak1 any plans for this ... to have PR with details in REDME ?

**Comment by rsvoboda** [comment]
@zhantemirov / @istraka can you check Mirek's notes - https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/69#issuecomment-562015656 and prepare PR for README so we can finalize this issue ...

**Comment by zhantemirov** [comment]
README.md updated in https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/174

**Comment by mnovak1** [comment]
https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/174 was merged

Closing
