### ISSUE TITLE
Migrate RHOAR QE coverage for MicroProfile Health

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#7]
Migrate relevant test coverage from 

 - https://github.com/rhoar-qe/thorntail-test-suite/tree/master/microprofile
 - https://github.com/thorntail-examples/health-check

**Comment by mnovak1** [comment]
@istraka  hi, can it be marked as done and closed?

**Comment by mnovak1** [comment]
Closing as test development for MP Health spec is done and this was part of the test plan.
