### ISSUE TITLE
serverLog.contains("FOOO") approach for server logs inspection

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/eap-microprofile-test-suite#78]
https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/74 introduces solution for watching logs using management model.

There was huge discussion about class and method name, this is followup issue for `serverLog.contains("FOOO")` approach.

Argument against this is: "we won't be implementing a server log we will be implementing its reader/checker whatever..."

`serverLog.contains("FOOO")` approach is more fluent/natural api, it looks nicer.

Code example:
```java
ServerLog serverLog = new ModelNodeServerLog(client, 50);
...
if ( serverLog.contains("WFLY00035") ) {
    ...
}
```

**Comment by mnovak1** [comment]
afaict this issue can be closed.

There is used `LogChecker` class for checking server log, example of usage:
```
try (final OnlineManagementClient client = ManagementClientProvider.onlineStandalone()) {
            final LogChecker logChecker = new ModelNodeLogChecker(client, 10, true);

            Assert.assertFalse(logChecker.logMatches(Pattern.compile(".*Foooqux 42.*")));
        }
```
This will be documented in guidelines to let everybody know there is such tooling.
