### ISSUE TITLE
Summary of Jenkins job/suite naming conventions issue we went through 

### ISSUE THREAD

**Issue by honza-kasik** [jboss-eap-qe/eap-microprofile-test-suite#84]
It is important to know that the testsuite ID which is used in specific suite definition is later use to filter test jobs. The test job are filtered based on a  fact whether their name contains the testsuite ID specified in `org.jboss.qe.pipeline.metadata.testing.Suite` extension.

Example:

```groovy
    /**
     * Suite for #MICROPROFILE_SUITE_ID
     */
    static class MicroprofileTestsuiteSuite extends Suite {
        MicroprofileTestsuiteSuite(String repo = null, String revision = null, CustomData customData = new CustomData()) {
            super(MICROPROFILE_SUITE_ID, repo, revision, customData)
        }
    }

```

`MICROPROFILE_SUITE_ID` is later used in testingMetadata delivered to pipeline job:

```json

    "name":"microprofile",
    "suites":{
        "microprofile-testsuite":{ #<-- This is the MICROPROFILE_SUITE_ID
            "repo":"https://github.com/jboss-qe-eap/eap-microprofile-test-suite.git",
            "revision":"master"
        }
    },
    "scope":"full"
}
```

Pipeline job later uses filtering based on testing metadata:

```groovy
final List testJobs = filterJobsByTestingMetadata(ALL_TEST_JOBS)
```

Which will initialize `testJobs` property to list of jobs from `ALL_TEST_JOBS` which name actually includes the value of `MICROPROFILE_SUITE_ID`.

It is important to keep in mind, that job naming matters.

**Comment by fabiobrz** [comment]
@honza-kasik thanks for creating an issue for this: do you think that https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-eap/ci-infrastructure-lib/blob/master/src/org/jboss/qe/pipeline/component/Microprofile.groovy isn't following guidelines at [1] and [2] or you think those identifiers should be changed?

**Comment by honza-kasik** [comment]
@fabiobrz +1 - More documentation never hurt anyone. You can make a PR for that...

**Comment by mnovak1** [comment]
I've added note about this job name dependency into tests-jobs:
https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-eap/tests-jobs/merge_requests/1228
